version: '2'
services:
  notebook:
    build:
      context: .
      args:
        http_proxy: "http://172.19.0.1:3128/"
        no_proxy: "localhost,ip6-localhost,ip6-loopback,127.0.0.1,::1,.local"
        HTTP_PROXY: "http://172.19.0.1:3128/"
        NO_PROXY: "localhost,ip6-localhost,ip6-loopback,127.0.0.1,::1,.local"
    command: start-notebook.sh --no-browser --ip 0.0.0.0
    ports:
      - "8888:8888"
    environment:
      http_proxy: "http://squid:3128/"
      no_proxy: "localhost,ip6-localhost,ip6-loopback,127.0.0.1,::1,.local"
      HTTP_PROXY: "http://squid:3128/"
      NO_PROXY: "localhost,ip6-localhost,ip6-loopback,127.0.0.1,::1,.local"
    volumes:
      - /data/notebook:/home/jake/notebook/
      - /data/notebook/.graphlab:/home/jake/.graphlab
    external_links:
      - squid_squid_1:squid
